// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package go_app

type CreateItemInput struct {
	Name          string  `json:"name"`
	Category      string  `json:"category"`
	Price         float64 `json:"price"`
	Qty           int     `json:"qty"`
	PurchaseStore *string `json:"purchase_store,omitempty"`
	PurchaseDate  *string `json:"purchase_date,omitempty"`
	Notes         *string `json:"notes,omitempty"`
}

type Item struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Category      string  `json:"category"`
	Price         float64 `json:"price"`
	Qty           int     `json:"qty"`
	PurchaseStore *string `json:"purchase_store,omitempty"`
	PurchaseDate  *string `json:"purchase_date,omitempty"`
	Notes         *string `json:"notes,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
