# Go Dockerfile
FROM golang:1.25.1

WORKDIR /app

# Copy go.mod and go.sum for dependency caching
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*
# Copy all source code
COPY . .

# Build the application
RUN go build -o main .

# Run the application
CMD ["/app/main"]