import type { Metadata } from "next";
import Link from 'next/link';
import Image from 'next/image';
import "@/styles/globals.css";

import React from 'react';

import { Providers } from './providers'
import Header from '@/components/base/Header'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="h-full overflow-hidden">
      <body className="flex flex-col min-h-screen">
        <Providers>
          <Header />
          <main className="flex-1 w-full mt-14 mb-12 overflow-y-auto">
            {children}
          </main>
          <footer className="flex-shrink-0 fixed bottom-0 left-0 right-0 h-12 flex justify-center items-center border-t bg-white">
            <a className="flex items-center">
            Copyright©
              <Image src="/sanuna.svg" alt="Vercel Logo" width={25} height={25} className="mx-1"/>
            All Rights Reserved
            </a>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
