// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Quantity    int     `json:"quantity"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Mutation struct {
}

type NewItem struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Quantity    int     `json:"quantity"`
}

type Query struct {
}

type UpdateItem struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Quantity    *int    `json:"quantity,omitempty"`
}
